# Generated by Django 4.1.7 on 2023-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='user_photos/')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
